version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: zillow_db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  property-api:
    build: .
    container_name: property-api
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - MONGO_URI=mongodb://mongo:27018/zillow_db
      - JWT_SECRET='my_super_secret_key'
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  mongo-data:
